export const languages = [
    { code: 'en-US', flag: '🇺🇸', name: 'English (USA)' },
    { code: 'en-GB', flag: '🇬🇧', name: 'English (UK)' },
    { code: 'en-AU', flag: '🇦🇺', name: 'English (Australia)' },
    { code: 'en-CA', flag: '🇨🇦', name: 'English (Canada)' },
    { code: 'ja-JP', flag: '🇯🇵', name: 'Japanese' },
    { code: 'zh-CN', flag: '🇨🇳', name: 'Chinese' },
    { code: 'de-DE', flag: '🇩🇪', name: 'German' },
    { code: 'hi-IN', flag: '🇮🇳', name: 'Hindi' },
    { code: 'fr-FR', flag: '🇫🇷', name: 'French (France)' },
    { code: 'fr-CA', flag: '🇨🇦', name: 'French (Canada)' },
    { code: 'ko-KR', flag: '🇰🇷', name: 'Korean' },
    { code: 'pt-BR', flag: '🇧🇷', name: 'Portuguese (Brazil)' },
    { code: 'pt-PT', flag: '🇵🇹', name: 'Portuguese (Portugal)' },
    { code: 'it-IT', flag: '🇮🇹', name: 'Italian' },
    { code: 'es-ES', flag: '🇪🇸', name: 'Spanish (Spain)' },
    { code: 'es-MX', flag: '🇲🇽', name: 'Spanish (Mexico)' },
    { code: 'id-ID', flag: '🇮🇩', name: 'Indonesian' },
    { code: 'nl-NL', flag: '🇳🇱', name: 'Dutch' },
    { code: 'tr-TR', flag: '🇹🇷', name: 'Turkish' },
    { code: 'fil-PH', flag: '🇵🇭', name: 'Filipino' },
    { code: 'pl-PL', flag: '🇵🇱', name: 'Polish' },
    { code: 'sv-SE', flag: '🇸🇪', name: 'Swedish' },
    { code: 'bg-BG', flag: '🇧🇬', name: 'Bulgarian' },
    { code: 'ro-RO', flag: '🇷🇴', name: 'Romanian' },
    { code: 'ar-SA', flag: '🇸🇦', name: 'Arabic (Saudi Arabia)' },
    { code: 'ar-AE', flag: '🇦🇪', name: 'Arabic (UAE)' },
    { code: 'cs-CZ', flag: '🇨🇿', name: 'Czech' },
    { code: 'el-GR', flag: '🇬🇷', name: 'Greek' },
    { code: 'fi-FI', flag: '🇫🇮', name: 'Finnish' },
    { code: 'hr-HR', flag: '🇭🇷', name: 'Croatian' },
    { code: 'ms-MY', flag: '🇲🇾', name: 'Malay' },
    { code: 'sk-SK', flag: '🇸🇰', name: 'Slovak' },
    { code: 'da-DK', flag: '🇩🇰', name: 'Danish' },
    { code: 'ta-IN', flag: '🇮🇳', name: 'Tamil' },
    { code: 'uk-UA', flag: '🇺🇦', name: 'Ukrainian' },
    { code: 'ru-RU', flag: '🇷🇺', name: 'Russian' }
];
