// Function to handle agent messages and display them
document.addEventListener('DOMContentLoaded', () => {
  const chatContainer = document.getElementById('chatContainer');

  const observer = new MutationObserver(() => {
    // Find messages generated by the ElevenLabs agent widget
    const widget = document.querySelector('elevenlabs-convai');
    const lastMessage = widget?.shadowRoot?.querySelector('.message');

    if (lastMessage && !lastMessage.classList.contains('processed')) {
      // Create a new div for the message
      const messageElement = document.createElement('div');
      messageElement.classList.add('message');
      messageElement.textContent = lastMessage.textContent;

      // Append to chat container
      chatContainer.appendChild(messageElement);

      // Mark message as processed
      lastMessage.classList.add('processed');
    }

    // Scroll chat to the bottom
    chatContainer.scrollTop = chatContainer.scrollHeight;
  });

  // Observe widget for changes
  const widget = document.querySelector('elevenlabs-convai');
  if (widget) {
    observer.observe(widget.shadowRoot, {
      childList: true,
      subtree: true,
    });
  }
});
